=== apasny/Task-2-XML-XSD-and-Web-Parsing/src/test/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="devices"
        xmlns:tns="devices"
        elementFormDefault="qualified">
    <element name="devices">
        <complexType>
            <sequence>
                <element name="device" type="tns:Device" minOccurs="0" maxOccurs="100"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Device">
        <sequence>
            <element name="name" type="string"/>
            <element name="price" type="double"/>
            <element name="cpu" minOccurs="0" type="tns:CPU"></element>
            <element name="graphics" minOccurs="0" type="tns:GraphicsCard "></element>
        </sequence>
        <attribute name="manufacturer">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Intel"></enumeration>
                    <enumeration value="AMD"></enumeration>
                    <enumeration value="Nvidia"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="CPU">
        <sequence>
            <element name="coresQuantity" type="positiveInteger"/>
            <element name="frequency" type="double"/>
            <element name="cache" type="positiveInteger"/>
            <element name="details" type="tns:Details"/>
        </sequence>
    </complexType>
    <complexType name="GraphicsCard ">
        <sequence>
            <element name="graphicMemory" type="positiveInteger"/>
            <element name="memoryBus" type="positiveInteger"/>
            <element name="bandwidth" type="positiveInteger"/>
            <element name="details" type="tns:Details"/>
        </sequence>
    </complexType>
    <complexType name="Details">
        <sequence>
            <element name="serialNumber" type="string"/>
            <element name="deviceID" type="string"/>
            <element name="releaseDate" type="positiveInteger"/>
        </sequence>
    </complexType>
</schema>

=== apasny/Task-2-XML-XSD-and-Web-Parsing/src/test/resources/devicesInvalid.xml
<?xml version="1.0" encoding="utf-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation ="http://www.example.com/devices devices.xsd">
    <cpu id="ID123">
        <name>i5</name
        <price>194</price>
        <manufacturer>Intel</manufacturer>
        <coresQuantity>6</coresQuantity>
        <frequency>4.2</frequency>
        <cache>32</cache>
        <details>
            <serialNumber>23145waddwa68746aw1</serialNumber>
            <deviceID>132w77-wda42aw-awd251</deviceID>
            <releaseDate>2019</releaseDate>
        </details>
    </cpu>
    <graphicsCard id="ID44">
        <name>rtx 2060</name>
        <price>652</price>
        <manufacturer>Nvidia</manufacturer>
        <graphicMemory>12</graphicMemory>
        <memoryBus>192</memoryBus>
        <bandwidth>306</bandwidth>
        <details>
            <serialNumber>f65q41fq</serialNumber>
            <deviceID>dq6-fqwf1-qw55</deviceID>
            <releaseDate>2018</releaseDate>
        </details>
    </graphicsCard>
</devices>
